### ISSUE TITLE
Unknown device

### ISSUE THREAD

**Issue by indiemini** [pocketmoon/EDTracker2#1]
I didn't really know where to put this, but I see that your github is being maintained. 

Every time I try to connect to EdTrackerUtilV2, it says: Unknown device; not monitoring.

In the smaller box, it says, 

Waiting for response from device on COM3
Error for connecting to COM3

I can't connect. I'm really disappointed. Help?

**Comment by pocketmoon** [comment]
Hi Brendan, is the edtracker a ready made one or one you've put together?
If its the latter has it been flashed with the software (calibration or
edtracker sketch)?

**Comment by pocketmoon** [comment]
Hi Brendan,  Are you using an Arduino Pro Micro like this one  ?

http://hobbycomponents.com/index.php/arduino-compatible-pro-micro.html

**Comment by indiemini** [comment]
Yep. Bought a Sparkfun pro micro.

**Comment by pocketmoon** [comment]
Have you tried loading some basic test sketches like blink (set led pin to
17 in the code) ?

 If that works then next step is to debug using the Arduino Serial Monitor
window.  Using the Arduino IDE load the calibration sketch.  open the
serial monitor and type V in the field at the top and click send.  Do you
get any output?

**Comment by indiemini** [comment]
Blink works... well... worked. My arduino now won't even show up in device manager (though it was before.) It might be faulty, so I'm going to order another. 

Before I start, though, may I ask for some tips on assembling it? On the off chance that I messed up, I was wondering if you have any tips.

**Comment by pocketmoon** [comment]
Hi,

We have a video of how to assemble one on our custom PCB:

https://www.youtube.com/watch?v=-tF0Yrim0mo&list=PLq1UUAbF3L1C_L_fGxge8rtqSzPo65EFQ

Other than that, perhaps get it working on breadboard first and then
transfer to permanent board ?

Can you post of picture of your board ? It may be a dry solder joint or
something similar.

Cheers,

Rob

**Comment by indiemini** [comment]
Hmm. I was already doing it on a breadboard. How much is your custom PCB, and how long does it take to ship?

**Comment by pocketmoon** [comment]
Hi ,

£5 for the PCB.  If you're outside the UK it's a usually £2 more for
postage.

Do you want to email me directly ?  pocketmoon@gmail.com .

Cheers,

**Comment by indiemini** [comment]
Sure! I think I'll buy one.

**Comment by indiemini** [comment]
Just dropped you an email.
