### ISSUE TITLE
Auto-centering needs to be 'tuneable' for Opentrack users

### ISSUE THREAD

**Issue by brumster** [pocketmoon/EDTracker2#3]
Current auto-centering works great for native joystick implemenation but is a bit too aggressive when using EDTracker at 1:1 linear axis scaling and external tracking software such as Opentrack... it kicks in and re-centers too aggressively.

Just needs to be able to be tuned in its effectiveness, maybe with a further scaling value that, when set to 0, can also disable the auto-centering entirely.

It should NOT be removed/disabled entirely because this will impact users using the device natively as a joystick direct to games, and lots of drift complaints will ensue, but an ability to change/tweak its effectiveness will be welcomed.

**Comment by pocketmoon** [comment]
Fixed in 2.20.5 Autocentre logic now applied to pre-scales yaw value.
