### ISSUE TITLE
Temp calculation in Invensense Motion Driver is wrong

### ISSUE THREAD

**Issue by brumster** [pocketmoon/EDTracker2#7]
inv_mpu.c for some reason has had the temperature calculation formula changed to a method that is not correct. As per the datasheet, the correct formula is : 

temperature = ((double) raw / 340.0) + 36.53;

I have tested this on an MPU6050 in conjunction with a laser temperature scanner and it is SPOT ON to .1 of a degree. The temp_offset seems to be incorrect applied/not necessary.

**Comment by pocketmoon** [comment]
Invenses shoddy library. Fixed. Returns temp is Q16 format.
